### ISSUE TITLE
Update example for Spring Boot 3

### ISSUE THREAD

**Issue by zoidyzoidzoid** [pactflow/example-provider-springboot#33]
Hi there!

I've been struggling to get an example working with Spring Boot 3, and finally got it working!

I think it's worth us updating the docs!

There is a spring6 package and doc, but it doesn't appear in the sidebar navigation?

https://github.com/pact-foundation/pact-jvm/blob/master/provider/spring6/README.md
https://github.com/pact-foundation/docs.pact.io/blob/master/website/docs/implementation_guides/jvm/provider/spring6.md?plain=1#L2
https://docs.pact.io/implementation_guides/jvm/provider/spring6

**Comment by YOU54F** [comment]
awesome stuff thanks @zoidbergwill 

there is a set of sync scripts which should pull them in, you can run them locally and map anything across that isn’t. some may be copied but not attached in the sidebars.json and as you noted it’s not shown.

just adding in the entry in the sidebars.json will allow it to attach to the nav and render the page with the sidebar etc
